# Generated by Django 3.0.6 on 2022-04-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('StockId', models.AutoField(primary_key=True, serialize=False)),
                ('StockName', models.CharField(max_length=500)),
                ('StockValue', models.FloatField()),
            ],
        ),
    ]
