# Generated by Django 3.0.6 on 2022-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stockId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=500)),
                ('stockName', models.CharField(max_length=500)),
            ],
        ),
    ]
